services:
    db:
        image: postgres:14.5-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: order_book
        networks:
            - order-book-network
        ports:
            - "5432:5432"
        volumes:
            - ./db/data:/var/lib/postgresql/data

networks:
    order-book-network:
        driver: bridge
